config/routes.rb
Rails.application.routes.draw do
  resources :phone_books

end

app/models/phone_book.rb
class PhoneBook < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/phone_books_controller.rb
class PhoneBooksController < ApplicationController
  before_action :set_phone_book, only: [:show, :edit, :update, :destroy]

  # GET /phone_books
  # GET /phone_books.json
  def index
    @phone_books = PhoneBook.all
  end

  # GET /phone_books/1
  # GET /phone_books/1.json
  def show
  end

  # GET /phone_books/new
  def new
    @phone_book = PhoneBook.new
  end

  # GET /phone_books/1/edit
  def edit
  end

  # POST /phone_books
  # POST /phone_books.json
  def create
    @phone_book = PhoneBook.new(phone_book_params)

    respond_to do |format|
      if @phone_book.save
        format.html { redirect_to @phone_book, notice: 'Phone book was successfully created.' }
        format.json { render :show, status: :created, location: @phone_book }
      else
        format.html { render :new }
        format.json { render json: @phone_book.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /phone_books/1
  # PATCH/PUT /phone_books/1.json
  def update
    respond_to do |format|
      if @phone_book.update(phone_book_params)
        format.html { redirect_to @phone_book, notice: 'Phone book was successfully updated.' }
        format.json { render :show, status: :ok, location: @phone_book }
      else
        format.html { render :edit }
        format.json { render json: @phone_book.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /phone_books/1
  # DELETE /phone_books/1.json
  def destroy
    @phone_book.destroy
    respond_to do |format|
      format.html { redirect_to phone_books_url, notice: 'Phone book was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_phone_book
      @phone_book = PhoneBook.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def phone_book_params
      params.require(:phone_book).permit(:name, :phone_number, :address)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/phone_books_helper.rb
module PhoneBooksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>App</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/phone_books/_form.html.erb
<%= form_for(@phone_book) do |f| %>
  <% if @phone_book.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@phone_book.errors.count, "error") %> prohibited this phone_book from being saved:</h2>

      <ul>
      <% @phone_book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :phone_number %><br>
    <%= f.text_field :phone_number %>
  </div>
  <div class="field">
    <%= f.label :address %><br>
    <%= f.text_field :address %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/phone_books/edit.html.erb
<h1>Editing phone_book</h1>

<%= render 'form' %>

<%= link_to 'Show', @phone_book %> |
<%= link_to 'Back', phone_books_path %>

app/views/phone_books/index.html.erb
<h1>Listing phone_books</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Phone number</th>
      <th>Address</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @phone_books.each do |phone_book| %>
      <tr>
        <td><%= phone_book.name %></td>
        <td><%= phone_book.phone_number %></td>
        <td><%= phone_book.address %></td>
        <td><%= link_to 'Show', phone_book %></td>
        <td><%= link_to 'Edit', edit_phone_book_path(phone_book) %></td>
        <td><%= link_to 'Destroy', phone_book, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Phone book', new_phone_book_path %>

app/views/phone_books/new.html.erb
<h1>New phone_book</h1>

<%= render 'form' %>

<%= link_to 'Back', phone_books_path %>

app/views/phone_books/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @phone_book.name %>
</p>

<p>
  <strong>Phone number:</strong>
  <%= @phone_book.phone_number %>
</p>

<p>
  <strong>Address:</strong>
  <%= @phone_book.address %>
</p>

<%= link_to 'Edit', edit_phone_book_path(@phone_book) %> |
<%= link_to 'Back', phone_books_path %>